name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# give permission to push to gh-pages
permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 15
    # Start a fresh Linux virtual machine (Ubuntu) to run the code
    runs-on: ubuntu-latest

    # Connect to GitHub Environments to access variables and secrets 
    environment: ${{ github.ref_name == 'main' && 'prod' || 'prod' }}

    env:
      # Set ENV variable for tests
      ENVIRONMENT: ${{ github.ref_name == 'main' && 'prod' || 'prod' }}

    steps:
    # Download code from github to runner
    - name: Checkout code
      uses: actions/checkout@v5

    # Build the .env file from GitHub variables and secrets
    - name: Create env file
      run: |
        echo "BASE_URL=${{ vars.BASE_URL }}" > .env.${{ env.ENVIRONMENT }}

    # Install python version from file
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: '.python-version'
        cache: 'pip'

    # Install all python packages
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # save playwright browsers so next run is faster
    - name: Cache Playwright browsers
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('requirements.txt') }}

    # Install the browsers (Chrome/Firefox)
    - name: Install Playwright Browsers
      run: python -m playwright install --with-deps

    # Run tests (extra config in pytest.ini)
    - name: Run tests
      run: pytest tests/

    # Try to get old report history
    - name: Get Allure history
      if: always()
      continue-on-error: true
      uses: actions/checkout@v5
      with:
        ref: gh-pages
        path: gh-pages

    # Build new allure report even if tests failed
    - name: Build Allure report
      if: always()
      uses: simple-elf/allure-report-action@v1.13
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: temp-allure-report
        allure_history: allure-report

    # Publish report even if tests failed
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: allure-report